language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "nightly"
before_script:
  - "pwd"
  - "ls -lart"
  - "ls -lart cmds"
  - "./cmds/decrypt.sh"
install: "echo aaa"
script: "echo bbb"
