language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "nightly"
before_script:
  - "./cmds/decrypt.sh"
script:
  - "python dsopz/dsopz.py login-serviceaccount -f test/dsopzit.secret.json"
  - "./test/test.sh"
