language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "nightly"
before_script:
  - "./cmds/before_script.sh"
install:
  - "./cmds/install.sh"
script:
  - "./cmds/script.sh"
